// <auto-generated />
using System;
using MatchMakings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchMakings.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250528100448_ChangeNotes")]
    partial class ChangeNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatchMakings.Core.Models.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaleId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchMakerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WomenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaleId");

                    b.HasIndex("MatchMakerId");

                    b.HasIndex("WomenId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.FamilyDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FamilyAbout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyRabbi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherAffiliation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherYeshiva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HealthStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("MaleId")
                        .HasColumnType("int");

                    b.Property<string>("MotherGraduateSeminar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPreviousName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ParentsStatus")
                        .HasColumnType("bit");

                    b.Property<int?>("WomenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaleId")
                        .IsUnique()
                        .HasFilter("[MaleId] IS NOT NULL");

                    b.HasIndex("WomenId")
                        .IsUnique()
                        .HasFilter("[WomenId] IS NOT NULL");

                    b.ToTable("FamilyDetails");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.MatchMaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaleId")
                        .HasColumnType("int");

                    b.Property<int?>("MaleId1")
                        .HasColumnType("int");

                    b.Property<int>("MatchMakerId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchMakerId1")
                        .HasColumnType("int");

                    b.Property<int?>("NumMeetings")
                        .HasColumnType("int");

                    b.Property<int>("WomenId")
                        .HasColumnType("int");

                    b.Property<int?>("WomenId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaleId");

                    b.HasIndex("MaleId1");

                    b.HasIndex("MatchMakerId");

                    b.HasIndex("MatchMakerId1");

                    b.HasIndex("WomenId");

                    b.HasIndex("WomenId1");

                    b.ToTable("MatchMakings");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchMakingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeetingPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumMeeting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchMakingId");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchMakerId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchMakerId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Male", b =>
                {
                    b.HasBaseType("MatchMakings.Core.Models.BaseUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeFrom")
                        .HasColumnType("int");

                    b.Property<int>("AgeTo")
                        .HasColumnType("int");

                    b.Property<bool>("AnOutsider")
                        .HasColumnType("bit");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackGround")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BigYeshiva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BurnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DriversLicense")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectationsFromPartner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacePaint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralAppearance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadCovering")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HealthCondition")
                        .HasColumnType("bit");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Hot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantTraitsIAmLookingFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantTraitsInMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kibbutz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoreInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Openness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PairingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredProfessionalPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredSeminarStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmallYeshiva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusVacant")
                        .HasColumnType("bit");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Man");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.MatchMaker", b =>
                {
                    b.HasBaseType("MatchMakings.Core.Models.BaseUser");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Community")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceInShidduchim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasChildrenInShidduchim")
                        .HasColumnType("bit");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsInternalMatchmaker")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSeminarGraduate")
                        .HasColumnType("bit");

                    b.Property<string>("LandlinePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchmakerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalClub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousWorkplaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearsInShidduchim")
                        .HasColumnType("int");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Address")
                                .HasColumnName("MatchMaker_Address");

                            t.Property("City")
                                .HasColumnName("MatchMaker_City");

                            t.Property("Email")
                                .HasColumnName("MatchMaker_Email");

                            t.Property("Occupation")
                                .HasColumnName("MatchMaker_Occupation");
                        });

                    b.HasDiscriminator().HasValue("Matchmaker");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Women", b =>
                {
                    b.HasBaseType("MatchMakings.Core.Models.BaseUser");

                    b.Property<string>("AdditionalEducationalInstitution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("AgeFrom")
                        .HasColumnType("int");

                    b.Property<int?>("AgeTo")
                        .HasColumnType("int");

                    b.Property<bool?>("AnOutsider")
                        .HasColumnType("bit");

                    b.Property<string>("Appearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackGround")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BurnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Club")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacePaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralAppearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadCovering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HealthCondition")
                        .HasColumnType("bit");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("HighSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantTraitsIMLookingFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportantTraitsInMe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestedInBoy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoreInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Openness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PairingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredSittingStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seminar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Smoker")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StatusVacant")
                        .HasColumnType("bit");

                    b.Property<string>("StudyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tz")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Users", t =>
                        {
                            t.Property("Address")
                                .HasColumnName("Women_Address");

                            t.Property("Age")
                                .HasColumnName("Women_Age");

                            t.Property("AgeFrom")
                                .HasColumnName("Women_AgeFrom");

                            t.Property("AgeTo")
                                .HasColumnName("Women_AgeTo");

                            t.Property("AnOutsider")
                                .HasColumnName("Women_AnOutsider");

                            t.Property("Appearance")
                                .HasColumnName("Women_Appearance");

                            t.Property("BackGround")
                                .HasColumnName("Women_BackGround");

                            t.Property("Beard")
                                .HasColumnName("Women_Beard");

                            t.Property("BurnDate")
                                .HasColumnName("Women_BurnDate");

                            t.Property("City")
                                .HasColumnName("Women_City");

                            t.Property("Class")
                                .HasColumnName("Women_Class");

                            t.Property("Club")
                                .HasColumnName("Women_Club");

                            t.Property("Country")
                                .HasColumnName("Women_Country");

                            t.Property("Email")
                                .HasColumnName("Women_Email");

                            t.Property("FacePaint")
                                .HasColumnName("Women_FacePaint");

                            t.Property("FatherPhone")
                                .HasColumnName("Women_FatherPhone");

                            t.Property("GeneralAppearance")
                                .HasColumnName("Women_GeneralAppearance");

                            t.Property("HeadCovering")
                                .HasColumnName("Women_HeadCovering");

                            t.Property("HealthCondition")
                                .HasColumnName("Women_HealthCondition");

                            t.Property("Height")
                                .HasColumnName("Women_Height");

                            t.Property("ImportantTraitsInMe")
                                .HasColumnName("Women_ImportantTraitsInMe");

                            t.Property("MoreInformation")
                                .HasColumnName("Women_MoreInformation");

                            t.Property("MotherPhone")
                                .HasColumnName("Women_MotherPhone");

                            t.Property("Occupation")
                                .HasColumnName("Women_Occupation");

                            t.Property("Openness")
                                .HasColumnName("Women_Openness");

                            t.Property("PairingType")
                                .HasColumnName("Women_PairingType");

                            t.Property("Phone")
                                .HasColumnName("Women_Phone");

                            t.Property("Smoker")
                                .HasColumnName("Women_Smoker");

                            t.Property("Status")
                                .HasColumnName("Women_Status");

                            t.Property("StatusVacant")
                                .HasColumnName("Women_StatusVacant");

                            t.Property("Suit")
                                .HasColumnName("Women_Suit");

                            t.Property("Tz")
                                .HasColumnName("Women_Tz");
                        });

                    b.HasDiscriminator().HasValue("Woman");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Contact", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.Male", "Male")
                        .WithMany("Acquaintances")
                        .HasForeignKey("MaleId");

                    b.HasOne("MatchMakings.Core.Models.MatchMaker", "MatchMaker")
                        .WithMany("Recommend")
                        .HasForeignKey("MatchMakerId");

                    b.HasOne("MatchMakings.Core.Models.Women", "Women")
                        .WithMany("Contacts")
                        .HasForeignKey("WomenId");

                    b.Navigation("Male");

                    b.Navigation("MatchMaker");

                    b.Navigation("Women");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.FamilyDetails", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.Male", "Male")
                        .WithOne("FamilyDetails")
                        .HasForeignKey("MatchMakings.Core.Models.FamilyDetails", "MaleId");

                    b.HasOne("MatchMakings.Core.Models.Women", "Women")
                        .WithOne("FamilyDetails")
                        .HasForeignKey("MatchMakings.Core.Models.FamilyDetails", "WomenId");

                    b.Navigation("Male");

                    b.Navigation("Women");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.MatchMaking", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.Male", "Male")
                        .WithMany()
                        .HasForeignKey("MaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.Male", null)
                        .WithMany("Matchings")
                        .HasForeignKey("MaleId1");

                    b.HasOne("MatchMakings.Core.Models.MatchMaker", "MatchMaker")
                        .WithMany()
                        .HasForeignKey("MatchMakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.MatchMaker", null)
                        .WithMany("Matches")
                        .HasForeignKey("MatchMakerId1");

                    b.HasOne("MatchMakings.Core.Models.Women", "Women")
                        .WithMany()
                        .HasForeignKey("WomenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.Women", null)
                        .WithMany("Matchings")
                        .HasForeignKey("WomenId1");

                    b.Navigation("Male");

                    b.Navigation("MatchMaker");

                    b.Navigation("Women");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Meeting", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.MatchMaking", "MatchMaking")
                        .WithMany("Meetings")
                        .HasForeignKey("MatchMakingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchMaking");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Note", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.MatchMaker", "MatchMaker")
                        .WithMany()
                        .HasForeignKey("MatchMakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.BaseUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("MatchMaker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.RolePermission", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.UserRole", b =>
                {
                    b.HasOne("MatchMakings.Core.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatchMakings.Core.Models.BaseUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.BaseUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.MatchMaking", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Male", b =>
                {
                    b.Navigation("Acquaintances");

                    b.Navigation("FamilyDetails");

                    b.Navigation("Matchings");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.MatchMaker", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Recommend");
                });

            modelBuilder.Entity("MatchMakings.Core.Models.Women", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("FamilyDetails");

                    b.Navigation("Matchings");
                });
#pragma warning restore 612, 618
        }
    }
}
